#!/usr/bin/env python
'''
This script is used to kick off a salt syndic daemon
'''

import os
import sys
try:
	sys.path = os.environ['SALT_PYTHONPATH'].split(os.pathsep) + sys.path
except KeyError:
	pass

from salt.scripts import salt_syndic


if __name__ == '__main__':
    salt_syndic()
