#!/usr/bin/env python
'''
Manage the authentication keys with salt-key
'''

import os
import sys
try:
	sys.path = os.environ['SALT_PYTHONPATH'].split(os.pathsep) + sys.path
except KeyError:
	pass

from salt.scripts import salt_key


if __name__ == '__main__':
    salt_key()
