#!/usr/bin/env python
'''
Start the salt-master
'''

import os
import sys
try:
	sys.path = os.environ['SALT_PYTHONPATH'].split(os.pathsep) + sys.path
except KeyError:
	pass

from salt.scripts import salt_master


if __name__ == '__main__':
    salt_master()
