#!/usr/bin/env python
'''
Execute the salt ssh system
'''

import os
import sys
try:
	sys.path = os.environ['SALT_PYTHONPATH'].split(os.pathsep) + sys.path
except KeyError:
	pass

from salt.scripts import salt_ssh


if __name__ == '__main__':
    salt_ssh()
