#!/usr/bin/env python
'''
Publish commands to the salt system from the command line on the master.
'''

import os
import sys
try:
	sys.path = os.environ['SALT_PYTHONPATH'].split(os.pathsep) + sys.path
except KeyError:
	pass
	
from salt.scripts import salt_main


if __name__ == '__main__':
    salt_main()
