#!/usr/bin/env python
'''
Directly call a salt command in the modules, does not require a running salt
minion to run.
'''

import os
import sys
try:
	sys.path = os.environ['SALT_PYTHONPATH'].split(os.pathsep) + sys.path
except KeyError:
	pass

from salt.scripts import salt_call


if __name__ == '__main__':
    salt_call()
